import pytest
from pydantic import ValidationError
from app.resources.sales_person_resource import SalesPersonLoginResource, SalesPersonCreateResource

# VALID and INVALID test data for SalesPersonLoginResource

# VALID and INVALID test data for SalesPersonCreateResource


# VALID TESTS FOR SalesPersonLoginResource

# INVALID TESTS FOR SalesPersonLoginResource

# VALID TESTS FOR SalesPersonCreateResource

# INVALID TESTS FOR SalesPersonCreateResource
